config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :texts
  devise_for :apps, controllers: {
    registrations: 'apps/registrations',
    passwords: 'apps/passwords'
  }  
  devise_scope :app do
    post 'apps/guest_sign_in', to: 'apps/sessions#new_guest'
  end
  # get "homes/index"
  root "posts#index"
  resources :menus
  resources :posts do
    resources :letters, only: [:create, :update]
  end
  resources :welcomtimes, only: [:create, :destroy]
  resources :contacts, only: [:index, :create]
  resources :posts do
    resource :saws, only: [:create, :destroy]
  end
  resources :absences, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :saturday_applications, only: [:index, :create, :new, :destroy, :update, :edit]
  resource :my_page
end

app/models/saturday_application.rb
class SaturdayApplication < ApplicationRecord
  SATURDAY_APPLICATION_LIST = %w[その他 仕事の為 病院受診の為 私用の為]
  validates :title, inclusion: { in: SATURDAY_APPLICATION_LIST }
  validates :date, :start_time, :end_time, presence: true
  belongs_to :app
end

app/controllers/saturday_applications_controller.rb
class SaturdayApplicationsController < ApplicationController
  def index
    @saturday_params = SaturdayApplications.find(params)
  end

  def new
  end

  def create
    keys = saturday_params_list.keys
    values = saturday_params_list.values
    params = values[0].zip(*values[1..-1]).map do |value|
      value.delete("")
      next if value.count != keys.count
      (keys.zip value).to_h
    end
    current_app.saturday_applications.create!(params.compact)
    redirect_to root_path, notice: "土曜申請を送信しました！"
  end

  def edit
    @saturday_application_list = SaturdayApplication::SATURDAY_APPLICATION_LIST.map { |title| [title, title] }

    @saturday_applications = current_app.saturday_applications.find(params[:id])
  end

  def update
    @saturday_applications = current_app.saturday_applications.find(params[:id])
    @saturday_applications.update!(saturday_params)
    redirect_to root_path, alert: "編集しました！"
  end

  def destroy
    @saturday_applications = current_app.saturday_applications.find(params[:id])
    @saturday_applications.destroy!
    redirect_to root_path, alert: "削除しました!"
  end

  private

  def saturday_params
    params.require(:saturday_application).permit(:date, :title, :start_time, :end_time)
  end

  def saturday_params_list
    params.require(:saturday_application).permit(date: [], start_time: [], end_time: [], title: [])
  end
end

app/views/saturday_applications/_saturday_application.html.erb
<tr>
  <td><%= l saturday_application.date %></td>
  <td><%= saturday_application.title %></td>
  <td><%= l saturday_application.start_time, format: :short %></td>
  <td><%= l saturday_application.end_time, format: :short %></td>
  <td><%= link_to edit_saturday_application_path(saturday_application),  class:"btn btn-outline-info" do %>
      <i class="fas fa-file-alt"></i>
    <% end %>
    <%= link_to saturday_application, class: 'btn btn-primary', method: :delete, data: { confirm: "削除しますか？" } do %>
      <i class="far fa-trash-alt"></i></td>
  <% end %>
</tr>

app/views/saturday_applications/create.html.erb
<h1>SaturdayApplications#create</h1>
<p>Find me in app/views/saturday_applications/create.html.erb</p>

app/views/saturday_applications/destroy.html.erb
<h1>SaturdayApplications#destroy</h1>
<p>Find me in app/views/saturday_applications/destroy.html.erb</p>

app/views/saturday_applications/edit.html.erb
<div class="container">
  <div class="container border p-3 my-5">
    <h1>土曜申請編集</h1>
    <%= form_with model: @saturday_applications, local: true do |form|  %>
      <div>
        <%= form.label :title, "日付" %>
        <div class="form-row">
          <div class="col-5">
            <%= form.text_field :date, class: "form-control", id: "saturday_application-edit-date" %>
          </div>
          <div class="col">
            <%= form.text_field :start_time, class:"form-control saturday-start" %>
          </div>
          <div class="d-flex align-items-center">〜</div>
          <div class="col"><%= form.text_field :end_time, class:"form-control saturday-end" %>
          </div>
        </div>
        <hr>
        <div class="form-group">
          <%= form.label :title, "理由" %>
          <%= form.select :title, @saturday_application_list, {}, class: "custom-select" %>
        </div>
        <div>
          <%= form.submit "投稿する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/saturday_applications/index.html.erb
<div class="modal-body">
  <p> <%= @saturday_application.title %></p>
  <p> <%= @saturday_application.start_time %></p>
  <p> <%= @saturday_application.end_time %></p>
  <p> <%= @saturday_application.date %></p>
</div>

app/views/saturday_applications/new.html.erb
<h1>SaturdayApplications#new</h1>
<p>Find me in app/views/saturday_applications/new.html.erb</p>

app/views/saturday_applications/update.html.erb
<h1>SaturdayApplications#update</h1>
<p>Find me in app/views/saturday_applications/update.html.erb</p>