config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :texts
  devise_for :apps, controllers: {
    registrations: 'apps/registrations',
    passwords: 'apps/passwords'
  }  
  devise_scope :app do
    post 'apps/guest_sign_in', to: 'apps/sessions#new_guest'
  end
  # get "homes/index"
  root "posts#index"
  resources :menus
  resources :posts do
    resources :letters, only: [:create, :update]
  end
  resources :welcomtimes, only: [:create, :destroy]
  resources :contacts, only: [:index, :create]
  resources :posts do
    resource :saws, only: [:create, :destroy]
  end
  resources :absences, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :saturday_applications, only: [:index, :create, :new, :destroy, :update, :edit]
  resource :my_page
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :app
  has_one :letter
  has_many :saws, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 2000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @letter = Letter.new
    @welcomtime = current_app.welcom_times
    @posts = Post.order(id: :desc).page(params[:page]).per(6)
    @absence = Absence.new
    @absences = current_app.absences.order("date")
    @absence_list = Absence::ABSENCE_LIST.map { |title| [title, title] }
    date_range = Date.current.beginning_of_month..Float::INFINITY
    @saturday_applications = current_app.saturday_applications.where(date: date_range).order(date: :asc)
    @saturday_application = SaturdayApplication.new
    @saturday_application_list = SaturdayApplication::SATURDAY_APPLICATION_LIST.map { |title| [title, title] }
  end

  # def show
  # end

  def new
    @post = Post.new
    @absence = Absence.new
    @saturday_application = SaturdayApplication.new
  end

  def create
    @absence.save!(absences_params)
    @saturday_application.save!(saturday_application_params)
    # current_app.posts.create!(post_params)
    # redirect_to action: :index
  end

  def edit
    @saturday_application_list = SaturdayApplication::SATURDAY_APPLICATION_LIST.map { |title| [title, title] }
  end

  # def update
  #   @post.update!(post_params)
  #   redirect_to (post_params), notice: "更新しました"
  # end

  def destroy
    @post.destroy!
    @absence.destroy!
    redirect_to posts alert: "削除しました"
  end

  # private

  # def set_post
  #   @post = Post.find(params[:id])
  # end

  # def correct_user
  #   @post = current_user.posts.find_by(id: params[:id])
  #   redirect_to root_path if @post.nill?
  # end

  # def post_params
  #   params.require(:post).permit(:title, :content, :image)
  # end
  def absences_params
    params.require(:absences).permit(:title, :content, :app_id)
  end

  def saturday_applications_params
    params.require(:saturday_applications).permit(:title, :content, :start_time, :end_time, :date, :app_id)
  end
end

app/views/posts/_absence.html.erb
<div class="text-center">
  <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#absenceModal">
    <i class="far fa-comment"></i> 欠席届
  </button>
</div>
<div class="container mt-5">
  <div class="modal fade" id="absenceModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalLabel">欠席届け</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with model: @absence, local: true do |form| %>
            <div class="field">
              <%= form.label :date , "日付"%>
              <%= form.text_field :date, id: "absence-date" %>
            </div>
            <div class="field">
              <%= form.label :title ,"理由"%>
              <%= form.select :title, @absence_list, {}, class: "custom-select" %>
            </div>
            <div class="field">
              <%= form.label :content,"症状" %>
              <%= form.rich_text_area :content %>
            </div>
            <div class="form-group">
              <%= form.file_field :image %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= form.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-sm-6 col-lg-4 border-white" style="height: 400px";>
  <div class="card" style="height: 400px";>
    <%= image_tag post.image_url(:thumb) %>
    <h3 class="card-title text-center"style="height: 400px";>タイトル
      <p><%= post.title %></p>
    </h3>
    <h3 class="card-text">
      <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#post-details-modal-<%= post.id %>">
        <i class="fas fa-highlighter"></i> 保育園での様子
      </button>
    </h3>
  </div>
</div>
<div class="modal fade" id="post-details-modal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="post-modal-title-<%= post.id %>" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="post-modal-title-<%= post.id %>"> 👶🍼</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p> <%= post.content %></p>
        <% if post.letter.present? %>
          <p> <%= post.letter.body_temperature %></p>
          <p> <%= post.letter.content %></p>
        <% end %>
      </div>
      <p>
        <div class="dropdown">
          <p>
            <div class="text-center">
              <button class="btn btn-primary " type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                返信
              </button>
            </div>
          </p>
          <%= render 'letters/letter', post: post %>
        </div>
      </p>
    </div>
  </div>
</div>

app/views/posts/_saturday_application.html.erb
<div class="text-center">
  <button type="button" class="btn btn-outline-warning" data-toggle="modal" data-target="#saturdayModal">
    <i class="far fa-comment"></i> 土曜申請書
  </button>
</div>
<div class="container mt-5">
  <div class="modal fade" id="saturdayModal" tabindex="-1" role="dialog" aria-labelledby="saturdayModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="saturdayModalLabel">土曜申請書</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with model: @saturday_application, local: true do |form| %>
            <% 5.times do |i| %>
              <div class="field">
                <%= form.label :date , "日付"%>
                <div class="form-row">
                  <div class="col-5">
                    <%= form.text_field :date, class: "form-control saturday", name: "saturday_application[date][]" %>
                  </div>
                  <div class="col">
                    <%= form.text_field :start_time, class:"form-control saturday-start", name: "saturday_application[start_time][]" %>
                  </div>
                  <div class="d-flex align-items-center">〜</div>
                  <div class="col"><%= form.text_field :end_time, class:"form-control saturday-end", name: "saturday_application[end_time][]" %>
                  </div>
                </div>
              </div>
              <div class="field">
                <%= form.label :title ,"理由"%>
                <%= form.select :title, @saturday_application_list, {}, class: "custom-select", name: "saturday_application[title][]" %>
              </div>
            <% end %>
            <div class="modal-footer">
              <button button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= form.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
document.getElementById('posts').insenrtAdjacentHTML('beforeend', '<%= j(render @posts ) %>'
document.getElementById('post_content').value = ''

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= form_with model: @post, local: true do |form| %>
  <div>
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "内容" %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.submit "送信" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<p class="my-4"></p>
<div class="container-login" style="max-width: 1200px;">
  <%= render 'shared/flash_messages' %>
  <hr>
  <p><%= current_app.title %></p>
  <%= image_tag current_app.image_url(:thumb) %>
  <div class="d-flex justify-content-end ">
    <div class="p-2 "><%= render 'absence' %></div>
    <div class="p-2 "><%= render 'saturday_application' %></div>
    <!-- Button trigger modal -->
    <div class="p-2 ">
      <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#absence-modal">
        欠席届一覧
      </button>
      <!-- Modal -->
      <div class="modal fade" id="absence-modal" tabindex="-1" role="dialog" aria-labelledby="absence-title-modal" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="absence-title-modal">欠席届一覧</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col2">日付</th>
                    <th scope="col2">症状</th>
                    <th scope="col2">詳細</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <%= render @absences %>
                </tbody>
              </table>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Button trigger modal -->
    <div class="p-2 ">
      <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#saturday-index-modal">
        土曜申請一覧
      </button>
      <!-- Modal -->
      <div class="modal fade" id="saturday-index-modal" tabindex="-1" role="dialog" aria-labelledby="saturdayTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="saturdayTitle">土曜申請一覧</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">日付</th>
                    <th scope="col">理由</th>
                    <th scope="col">登園時間</th>
                    <th scope="col">お迎え時間</th>
                    <th></th>
                  </thead>
                  <tbody>
                    <%= render @saturday_applications %>
                  </tbody>
                </table>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="posts">
      <div class="row">
        <%= render @posts %>
        <%= link_to "プロフィール", edit_my_page_path %>
      </div>
      <a href="https://1drv.ms/w/s!AmbzeXYYggEqjmztLc7bq-_cnBnO">お知らせ</a>
      <a href="https://1drv.ms/w/s!AmbzeXYYggEqjmqEuLo-juA4N6oZ">お知らせ２</a>
      <%= paginate @posts %>
      <p>年間行事</p>
    </div>
    <div class="googleCalendar">
      <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;showTitle=1" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>    </div>
  </div>
</div>

app/views/posts/new.html.erb
<!-- Button trigger modal -->

app/views/posts/show.html.erb
<div class="container-login">
  <h1>投稿詳細</h1>
  <p>タイトル <%= @post.title %></p>
  <p>本文 <%= @post.content %></p>
  <%= image_tag @post.image_url(:thumb) if @post.image.present? %>
</div>