config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :texts
  devise_for :apps, controllers: {
    registrations: 'apps/registrations',
    passwords: 'apps/passwords'
  }  
  devise_scope :app do
    post 'apps/guest_sign_in', to: 'apps/sessions#new_guest'
  end
  # get "homes/index"
  root "posts#index"
  resources :menus
  resources :posts do
    resources :letters, only: [:create, :update]
  end
  resources :welcomtimes, only: [:create, :destroy]
  resources :contacts, only: [:index, :create]
  resources :posts do
    resource :saws, only: [:create, :destroy]
  end
  resources :absences, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :saturday_applications, only: [:index, :create, :new, :destroy, :update, :edit]
  resource :my_page
end

app/models/text.rb
class Text < ApplicationRecord
  has_rich_text :content
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: "Text was successfully created." }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: "Text was successfully updated." }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: "Text was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_text
    @text = Text.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def text_params
    params.require(:text).permit(:title, :content)
  end
end

app/views/texts/_form.html.erb
<%= form_with(model: text, local: true) do |form| %>
  <% if text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
        <% text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Texts</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.title %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
        <td colspan="4"><%= text.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @text.title %>
  <%= @text.content %>
</p>
<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>