config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :texts
  devise_for :apps, controllers: {
    registrations: 'apps/registrations',
    passwords: 'apps/passwords'
  }  
  devise_scope :app do
    post 'apps/guest_sign_in', to: 'apps/sessions#new_guest'
  end
  # get "homes/index"
  root "posts#index"
  resources :menus
  resources :posts do
    resources :letters, only: [:create, :update]
  end
  resources :welcomtimes, only: [:create, :destroy]
  resources :contacts, only: [:index, :create]
  resources :posts do
    resource :saws, only: [:create, :destroy]
  end
  resources :absences, only: [:index, :create, :new, :destroy, :update, :edit]
  resources :saturday_applications, only: [:index, :create, :new, :destroy, :update, :edit]
  resource :my_page
end

app/models/absence.rb
class Absence < ApplicationRecord
  ABSENCE_LIST = %w[その他 インフルエンザ 溶連菌 コロナ 結膜炎 アデノ プール熱]
  validates :title, inclusion: { in: ABSENCE_LIST }
  belongs_to :app
  has_rich_text :content
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/app.rb
class App < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :welcom_times, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :letters, dependent: :destroy
  has_many :saws, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :saturday_applications, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable,
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_one_attached :image

  mount_uploader :image, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |app|
      app.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :app
  has_rich_text :content
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :app
  belongs_to :post
  validates :app_id, uniqueness: { scope: :post_id }
  validates :body_temperature, numericality: true
  validates :post_id, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :snack_image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :app
  has_one :letter
  has_many :saws, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 2000 }
end

app/models/saturday_application.rb
class SaturdayApplication < ApplicationRecord
  SATURDAY_APPLICATION_LIST = %w[その他 仕事の為 病院受診の為 私用の為]
  validates :title, inclusion: { in: SATURDAY_APPLICATION_LIST }
  validates :date, :start_time, :end_time, presence: true
  belongs_to :app
end

app/models/saw.rb
class Saw < ApplicationRecord
  belongs_to :app
  belongs_to :post
  validates :app_id, presence: true, uniqueness: { scope: :post_id }
  validates :post_id, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
  has_rich_text :content
end

app/models/welcom_time.rb
class WelcomTime < ApplicationRecord
  belongs_to :app
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :app
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[show edit update destroy]

  def index
    @menus = Menu.order(id: :asc)
    @menus = Menu.all.page(params[:page]).per(5)
  end

  def new
    @menu = Menu.new
  end

  def create
    menu = Menu.create!(menu_params)
  end

  def show
  end

  def edit
  end

  def update
    @menu.update!(menu_params)
    redirect_to @menu
  end

  def destroy
    @menu.destroy!
    redirect_to @menu
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:title, :content, :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @letter = Letter.new
    @welcomtime = current_app.welcom_times
    @posts = Post.order(id: :desc).page(params[:page]).per(6)
    @absence = Absence.new
    @absences = current_app.absences.order("date")
    @absence_list = Absence::ABSENCE_LIST.map { |title| [title, title] }
    date_range = Date.current.beginning_of_month..Float::INFINITY
    @saturday_applications = current_app.saturday_applications.where(date: date_range).order(date: :asc)
    @saturday_application = SaturdayApplication.new
    @saturday_application_list = SaturdayApplication::SATURDAY_APPLICATION_LIST.map { |title| [title, title] }
  end

  # def show
  # end

  def new
    @post = Post.new
    @absence = Absence.new
    @saturday_application = SaturdayApplication.new
  end

  def create
    @absence.save!(absences_params)
    @saturday_application.save!(saturday_application_params)
    # current_app.posts.create!(post_params)
    # redirect_to action: :index
  end

  def edit
    @saturday_application_list = SaturdayApplication::SATURDAY_APPLICATION_LIST.map { |title| [title, title] }
  end

  # def update
  #   @post.update!(post_params)
  #   redirect_to (post_params), notice: "更新しました"
  # end

  def destroy
    @post.destroy!
    @absence.destroy!
    redirect_to posts alert: "削除しました"
  end

  # private

  # def set_post
  #   @post = Post.find(params[:id])
  # end

  # def correct_user
  #   @post = current_user.posts.find_by(id: params[:id])
  #   redirect_to root_path if @post.nill?
  # end

  # def post_params
  #   params.require(:post).permit(:title, :content, :image)
  # end
  def absences_params
    params.require(:absences).permit(:title, :content, :app_id)
  end

  def saturday_applications_params
    params.require(:saturday_applications).permit(:title, :content, :start_time, :end_time, :date, :app_id)
  end
end

app/controllers/saws_controller.rb
class SawsController < ApplicationController
  def new
    saws = Saw.new
  end

  def create
    @post = Post.find(params[:post_id])
    current_app.saws.create!(post_id: @post.id)
    # redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_app.saws.find_by(post_id: @post.id).destroy!
    # redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalAppSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if app_signed_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
          <a class="navbar-brand" href="#">やんばる保育園</a>
          <div class="grid-6">
            <%= link_to "ログイン", new_app_session_path, class: 'post' %>
            <%= link_to "新規登録", new_app_registration_path, class: 'post' %>
          </div>
        </header>
      <% end %>
      <%= yield %>
    </body>
  </html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <hr>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <p style="color: <%= msg_type == 'notice' ? 'green' : 'red' %>;"><%= msg %></p>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <p><%= f.label :title, "タイトル" %> <%= f.text_field :title %></p>
  <p><%= f.label :image, "画像" %> <%= f.file_filed :image, accept: "image/png,image/jpeg,image/gif" %></p>
  <p><%= f.submit "送信" %></p>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">やんばる保育園</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "お便り帳", posts_path, class: 'navbar-brand' %>
          <i class="fas fa-envelope-open-text"></i>
        </li>
        <li class="nav-item active">
          <%= link_to "お問合せ", contacts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "献立", menus_path, class: 'navbar-brand' %>
        </li>
        <li class="nav-item active">
          <%= button_to "登園", welcomtimes_path, name: 'garden', class:"navbar-brand", method: :post %>
        </li>
        <li class="nav-item active">
          <%= button_to "降園", welcomtimes_path, name: 'garden', class:"navbar-brand", method: :post %>
        </li>
        <li class="nav-item active">
          <%= link_to 'ログアウト', destroy_app_session_path, method: :delete, class: 'nav-link',data: { confirm: "ログアウトしますか？" }  %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_new.html.erb
<div class="container mt-5">
  <div class="modal fade" id="exampleModalLabel" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ModalLabel">新規投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= form_with model: @post, local: true do |form| %>
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title %>
            </div>
            <div class="field">
              <%= form.label :content %>
              <%= form.rich_text_area :content %>
            </div>
            <div class="form-group">
              <%= form.file_field :image %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= form.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>